server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: esbgw123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  main:
    allow-bean-definition-overriding: true

jwt:
  secret: JahSc5PPUXIYh3QZGKib+mB0cVRH8tJIsVbZo4xAEmlKNMbDDls4DUwHiKYJP92CdZ8xGFlJvIaLip6LflHTrQ==